version: "3"

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./app/:/usr/src/app
    command: flask run --host=0.0.0.0

  postgres:
    ports:
      - "5432:5432"
