version: "3"

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./app/:/usr/src/app
    command: flask run --host=0.0.0.0
    depends_on:
      - postgres
  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  postgres_data:
  app_data:
