version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/home/flask/app/web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./app/:/home/flask/app/web
    command: flask run --host=0.0.0.0
    depends_on:
      - postgres
  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  postgres_data_dev:
