version: "3"

services:
  app:
    build: ./app
    volumes:
      - app_data:/usr/src/app/project/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    depends_on:
      - app
    command: "nginx"
  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    expose:
      - "5432"
volumes:
  postgres_data:
  app_data:
