version: "3"

services:
  app:
    build: ./app
    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
    ports:
      - "5000"
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    volumes:
      - /www/static
    depends_on:
      - app
  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - postgres_data_prod:/var/lib/postgresql
    expose:
      - "5432"
volumes:
  postgres_data_prod:
