version: "3.5"

services:
  flask:
    container_name: wtp_flask
    build: ./app
    volumes:
      - ./app:/home/flask/app/web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - ./app/:/home/flask/app/web
    command: flask run --host=0.0.0.0
    depends_on:
      - postgres
    networks:
      - wtp_net
  postgres:
    container_name: wtp_postgres
    restart: always
    build: ./postgresql
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - wtp_net
volumes:
  postgres_data_dev:
networks:
  wtp_net:
    name: wtp_net
